# Generated by Django 3.2.8 on 2021-11-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='information',
            field=models.CharField(default='No information available', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='artwork',
            field=models.CharField(default='https://res.cloudinary.com/dwc4kzyds/image/upload/v1636832140/Image/logo.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='url_player',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
