# Generated by Django 3.2.8 on 2021-10-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='url_player',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
